version: 1.0.{build}
image:
- Ubuntu
- Visual Studio 2017
install:
- git submodule update --init --recursive
build_script:
- sh: ./ci-build.sh
- cmd: call .\ci-build.cmd
artifacts:
- path: cimgui/build/Release/cimgui.so
  name: cimgui.so
- path: cimgui\build\x64\Release\cimgui.win-x64.dll
  name: cimgui.win-x64.dll
- path: cimgui\build\x86\Release\cimgui.win-x86.dll
  name: cimgui.win-x86.dll

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Native Release ($(APPVEYOR_BUILD_WORKER_IMAGE))'
  provider: GitHub
  auth_token:
    secure: DEGIcombPNY+d9ZUR4321jSr5Y+i03DkeiLvfEhzJtOFmaZrXVdS8B14mJQyqw8c
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
