name: CI

# Controls when the workflow will run
on:
  create:

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ReleaseType:
        description: 'Release or Debug'
        required: true
        default: 'Release'

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: ubuntu-24.04-arm
          - os: windows-latest
            architecture: x64
          - os: windows-latest
            architecture: x86
          - os: windows-latest
            architecture: arm64
          - os: windows-latest
            architecture: arm

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET
        if: matrix.os == 'windows-latest'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Build source package
        if: matrix.os == 'windows-latest' && matrix.architecture == 'x64'
        run: dotnet pack -c Release BUTR.ImGui.NET.SourceBuild.csproj
        shell: bash

      - name: Upload source package
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest' && matrix.architecture == 'x64'
        with:
          name: package-source
          path: bin\Packages\Release\*.nupkg

      - name: Publish source package to GPR
        if: matrix.os == 'windows-latest' && matrix.architecture == 'x64'
        run: dotnet nuget push bin\Packages\Release\*.nupkg -s https://nuget.pkg.github.com/BUTR/index.json -k ${{ secrets.GITHUB_TOKEN }} 
        # error can be fixed afterwards and job can be re-triggered
        continue-on-error: true

      - name: Publish source package to NuGet
        if: matrix.os == 'windows-latest' && matrix.architecture == 'x64'
        run: dotnet nuget push bin\Packages\Release\*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}}
        # error can be fixed afterwards and job can be re-triggered
        continue-on-error: true

      - name: Build ${{ github.event.inputs.ReleaseType || 'Release' }}
        run:  |
              if [[ "$RUNNER_OS" == "Windows" ]]; then
                ./ci-build.cmd ${{ github.event.inputs.ReleaseType || 'Release' }} ${{ matrix.architecture }}
              else
                ./ci-build.sh ${{ github.event.inputs.ReleaseType || 'Release' }}
              fi
        shell: bash

      - name: Upload win-${{ matrix.architecture }} ${{ github.event.inputs.ReleaseType || 'Release' }}
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: win-${{ matrix.architecture }}
          path: cimgui-custom\build\${{ matrix.architecture }}\${{ github.event.inputs.ReleaseType || 'Release' }}\*

      - name: Upload ${{ matrix.os }}-${{ matrix.architecture }} ${{ github.event.inputs.ReleaseType || 'Release' }}
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux-x64
          path: cimgui-custom/build/${{ github.event.inputs.ReleaseType || 'Release' }}/*

      - name: Upload ${{ matrix.os }}-${{ matrix.architecture }} ${{ github.event.inputs.ReleaseType || 'Release' }}
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-24.04-arm'
        with:
          name: linux-arm64
          path: cimgui-custom/build/${{ github.event.inputs.ReleaseType || 'Release' }}/*

      - name: Upload ${{ matrix.os }} ${{ github.event.inputs.ReleaseType || 'Release' }}
        uses: actions/upload-artifact@v4
        if: matrix.os == 'macos-latest'
        with:
          name: osx
          path: cimgui-custom/build/${{ github.event.inputs.ReleaseType || 'Release' }}/*

      - name: Upload Json Files
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest' && matrix.architecture == 'x64'
        with:
          name: JsonFiles
          path: cimgui-custom\generator\output\*.json

  CreateNativePackage:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Build package
        run: dotnet pack -c Release BUTR.ImGui.NET.Native.csproj
        shell: bash

      - name: Publish source package to GPR
        run: dotnet nuget push bin/Packages/Release/*.nupkg -s https://nuget.pkg.github.com/BUTR/index.json -k ${{ secrets.GITHUB_TOKEN }} 
        # error can be fixed afterwards and job can be re-triggered
        continue-on-error: true

      - name: Publish source package to NuGet
        run: dotnet nuget push bin/Packages/Release/*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}}
        # error can be fixed afterwards and job can be re-triggered
        continue-on-error: true